# substitutions:

#   _VARIABLES_JSON: gs://config222/variables.json

steps:

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ["run", "create-env"]
    env:
      - '_NODE_ENV=  $_NODE_ENV'
      - '_BUCKET_NAME= $_BUCKET_NAME'
      - '_PROJECT_ID= $PROJECT_ID'
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        # Build and push Docker image using the REPOSITORY_NAME environment variable

        docker build -t "us-central1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/dmyimage" .

        docker push "us-central1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/dmyimage"

  - name: 'gcr.io/cloud-builders/gcloud'

    args: [

      'run', 'deploy', 'dev_cisco',

      '--image', "us-central1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/dmyimage",

      '--platform', 'managed',

      '--region', 'us-central1',

      '--port', '7000',

      '--allow-unauthenticated'  # Add this line if you want to allow unauthenticated access (for public services)

    ]

options:

  dynamicSubstitutions: true